server:
  session:
    store-type: redis
    #  timeout: 3600s
    redis:
      flush-mode: on_save
      namespace: spring:session
  tomcat :
    url-encoding : UTF-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8768/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-0iw59mny5050jpg70jo.mysql.japan.rds.aliyuncs.com:3306/zongbang-alipay?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: kent
    password: 9asdasd7dwgdo7$as8d)asd
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 5000
    pool:
      max-idle: 200
      min-idle: 10
      max-active: 1000
      max-wait: -1


#以上为本地测试配置文件